
name: "cla-bot"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: "MLCommons CLA bot check"
        if: (github.event.comment.body == 'recheck') || github.event_name == 'pull_request_target'
        # Alpha Release
        uses: pgmpablo157321/github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.MLCOMMONS_BOT_CLA_TOKEN }}
        with:
          path-to-signatures: 'cla-bot/v1/cla.json'
          path-to-document: 'https://github.com/contributor-assistant/github-action/blob/master/SAPCLA.md' # e.g. a CLA or a DCO document
          
